In [28]:
import torch
import numpy as np
import matplotlib.pyplot as plt

### NumPy and PyTorch

In [29]:
MAT1 = torch.rand(size=(2,3,4),
                  dtype=torch.float64)

In [30]:
arr = np.arange(3, 1000, 6)

In [31]:
VEC = torch.from_numpy(arr).type(torch.float64)

In [32]:
VEC

tensor([  3.,   9.,  15.,  21.,  27.,  33.,  39.,  45.,  51.,  57.,  63.,  69.,
         75.,  81.,  87.,  93.,  99., 105., 111., 117., 123., 129., 135., 141.,
        147., 153., 159., 165., 171., 177., 183., 189., 195., 201., 207., 213.,
        219., 225., 231., 237., 243., 249., 255., 261., 267., 273., 279., 285.,
        291., 297., 303., 309., 315., 321., 327., 333., 339., 345., 351., 357.,
        363., 369., 375., 381., 387., 393., 399., 405., 411., 417., 423., 429.,
        435., 441., 447., 453., 459., 465., 471., 477., 483., 489., 495., 501.,
        507., 513., 519., 525., 531., 537., 543., 549., 555., 561., 567., 573.,
        579., 585., 591., 597., 603., 609., 615., 621., 627., 633., 639., 645.,
        651., 657., 663., 669., 675., 681., 687., 693., 699., 705., 711., 717.,
        723., 729., 735., 741., 747., 753., 759., 765., 771., 777., 783., 789.,
        795., 801., 807., 813., 819., 825., 831., 837., 843., 849., 855., 861.,
        867., 873., 879., 885., 891., 89

In [33]:
arr[0] = 123.232323

In [34]:
VEC

tensor([  3.,   9.,  15.,  21.,  27.,  33.,  39.,  45.,  51.,  57.,  63.,  69.,
         75.,  81.,  87.,  93.,  99., 105., 111., 117., 123., 129., 135., 141.,
        147., 153., 159., 165., 171., 177., 183., 189., 195., 201., 207., 213.,
        219., 225., 231., 237., 243., 249., 255., 261., 267., 273., 279., 285.,
        291., 297., 303., 309., 315., 321., 327., 333., 339., 345., 351., 357.,
        363., 369., 375., 381., 387., 393., 399., 405., 411., 417., 423., 429.,
        435., 441., 447., 453., 459., 465., 471., 477., 483., 489., 495., 501.,
        507., 513., 519., 525., 531., 537., 543., 549., 555., 561., 567., 573.,
        579., 585., 591., 597., 603., 609., 615., 621., 627., 633., 639., 645.,
        651., 657., 663., 669., 675., 681., 687., 693., 699., 705., 711., 717.,
        723., 729., 735., 741., 747., 753., 759., 765., 771., 777., 783., 789.,
        795., 801., 807., 813., 819., 825., 831., 837., 843., 849., 855., 861.,
        867., 873., 879., 885., 891., 89

In [35]:
arr

array([123,   9,  15,  21,  27,  33,  39,  45,  51,  57,  63,  69,  75,
        81,  87,  93,  99, 105, 111, 117, 123, 129, 135, 141, 147, 153,
       159, 165, 171, 177, 183, 189, 195, 201, 207, 213, 219, 225, 231,
       237, 243, 249, 255, 261, 267, 273, 279, 285, 291, 297, 303, 309,
       315, 321, 327, 333, 339, 345, 351, 357, 363, 369, 375, 381, 387,
       393, 399, 405, 411, 417, 423, 429, 435, 441, 447, 453, 459, 465,
       471, 477, 483, 489, 495, 501, 507, 513, 519, 525, 531, 537, 543,
       549, 555, 561, 567, 573, 579, 585, 591, 597, 603, 609, 615, 621,
       627, 633, 639, 645, 651, 657, 663, 669, 675, 681, 687, 693, 699,
       705, 711, 717, 723, 729, 735, 741, 747, 753, 759, 765, 771, 777,
       783, 789, 795, 801, 807, 813, 819, 825, 831, 837, 843, 849, 855,
       861, 867, 873, 879, 885, 891, 897, 903, 909, 915, 921, 927, 933,
       939, 945, 951, 957, 963, 969, 975, 981, 987, 993, 999])

In [36]:
VEC[0] = 1919.92

In [37]:
VEC[0]

tensor(1919.9200, dtype=torch.float64)

In [38]:
arr[0]

123

In [39]:
TEN1 = torch.rand(size=(3, 2, 1))

In [40]:
np_arr = TEN1.numpy()

In [41]:
np_arr

array([[[0.8696777 ],
        [0.47100097]],

       [[0.8959531 ],
        [0.75479484]],

       [[0.6210168 ],
        [0.45536035]]], dtype=float32)

In [42]:
TEN1[0, 0, 0]

tensor(0.8697)

In [43]:
np_arr[0, 0, 0] = 1

In [44]:
TEN1[0, 0, 0]

tensor(1.)

In [45]:
np_arr[0, 0, 0]

1.0

### PyTorch Reproducibility

To reduce the randomness and make the code reproducible, we need to define a **random seed**.

In [46]:
random_tensor_A = torch.rand(size=(3, 3))
random_tensor_B = torch.rand(size=(3, 3))

In [47]:
random_tensor_A == random_tensor_B

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [55]:
RANDOM_SEED = 2091106
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(size=(3, 4))
random_tensor_D = torch.rand(size=(3, 4))

In [56]:
random_tensor_C == random_tensor_D

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [57]:
torch.manual_seed(RANDOM_SEED)
random_tensor_E = torch.rand(size=(3, 4))

In [58]:
random_tensor_C == random_tensor_E

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

### Running Tensors and Pytorch objects on GPUs

In [59]:
torch.cuda.is_available()

False

### Device Agnostic Code

In [62]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [63]:
device

'cpu'