In [5]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
print(torch.__version__)

1.12.1


## Tensors

What is a tensor?

A tensor is a multidimensional array of numerical values that is used to represent data, such as images, sound, or text.

**A *vector* is a special case of a tensor, where the tensor has only one dimension.**

In [13]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [14]:
scalar.ndim

0

In [16]:
number = scalar.item()

In [17]:
type(number)

int

In [18]:
# vector
vector = torch.tensor([9, 87])

In [19]:
vector

tensor([ 9, 87])

In [20]:
vector.ndim

1

In [21]:
vector.shape

torch.Size([2])

In [23]:
vector.size()

torch.Size([2])

In [27]:
# MATRIX
mat = torch.tensor([[2, 4],
                    [34, 12],
                    [34, 34]])
mat

tensor([[ 2,  4],
        [34, 12],
        [34, 34]])

In [28]:
mat.size()

torch.Size([3, 2])

In [29]:
mat.ndim

2

In [30]:
mat[0]

tensor([2, 4])

In [32]:
mat[0, 1]

tensor(4)

In [49]:
# Tensor
tensor1 = torch.tensor([[[12, 32],
                     [34, 12],
                    [56, 98],
                    [98, 23]]])
tensor1

tensor([[[12, 32],
         [34, 12],
         [56, 98],
         [98, 23]]])

In [50]:
tensor1.size()

torch.Size([1, 4, 2])

In [51]:
tensor1.ndim

3

In [54]:
tensor2 = torch.tensor([[[[1, 2],
                          [3, 4]],
                        [[5, 6],
                         [7, 8]]],
                        [[[1, 2],
                          [3, 4]],
                        [[5, 6],
                         [7, 8]]]])
tensor2

tensor([[[[1, 2],
          [3, 4]],

         [[5, 6],
          [7, 8]]],


        [[[1, 2],
          [3, 4]],

         [[5, 6],
          [7, 8]]]])

In [56]:
tensor2.size()

torch.Size([2, 2, 2, 2])

In [57]:
tensor2.ndim

4

### Random Tensors

Random tensors are important because the way many neural networks learn is to start with a tensor full of random values and adjust those initial values to better represent the data

In [58]:
RANDOM = torch.rand(3, 4)

In [59]:
RANDOM

tensor([[0.0236, 0.4351, 0.4529, 0.7417],
        [0.8247, 0.4715, 0.2597, 0.6114],
        [0.9600, 0.0452, 0.7846, 0.4943]])

In [61]:
RANDOM.ndim

2

In [62]:
RANDOM = torch.rand(3, 5, 3, 2)

In [63]:
RANDOM

tensor([[[[0.8652, 0.9996],
          [0.8874, 0.8928],
          [0.8958, 0.6703]],

         [[0.4691, 0.4252],
          [0.6189, 0.6108],
          [0.7296, 0.6768]],

         [[0.1083, 0.9960],
          [0.8707, 0.5810],
          [0.8811, 0.6577]],

         [[0.6764, 0.0246],
          [0.1408, 0.3932],
          [0.8925, 0.9761]],

         [[0.8334, 0.7127],
          [0.8976, 0.7271],
          [0.0352, 0.6585]]],


        [[[0.2856, 0.2164],
          [0.7483, 0.9515],
          [0.1868, 0.9828]],

         [[0.8804, 0.7366],
          [0.8868, 0.4760],
          [0.4055, 0.7161]],

         [[0.0278, 0.2860],
          [0.6647, 0.4568],
          [0.0588, 0.9449]],

         [[0.4615, 0.6554],
          [0.9667, 0.3992],
          [0.1033, 0.1313]],

         [[0.4374, 0.1282],
          [0.4969, 0.2843],
          [0.5544, 0.7888]]],


        [[[0.5121, 0.5883],
          [0.1441, 0.5862],
          [0.1095, 0.9177]],

         [[0.3600, 0.3306],
          [0.9608, 0.4

In [64]:
RANDOM.size()

torch.Size([3, 5, 3, 2])

In [65]:
RANDOM.ndim

4

In [66]:
IMG = torch.rand(size=(224, 224, 3))

In [67]:
IMG

tensor([[[0.2231, 0.8902, 0.1490],
         [0.5322, 0.5966, 0.0445],
         [0.0319, 0.0191, 0.5291],
         ...,
         [0.1355, 0.8370, 0.0905],
         [0.4172, 0.0954, 0.9776],
         [0.2268, 0.4674, 0.3733]],

        [[0.8949, 0.2967, 0.6087],
         [0.2735, 0.6404, 0.1013],
         [0.0465, 0.3265, 0.2249],
         ...,
         [0.6174, 0.5624, 0.9369],
         [0.2097, 0.3713, 0.0093],
         [0.8461, 0.6946, 0.4741]],

        [[0.6751, 0.3556, 0.3992],
         [0.7853, 0.8068, 0.7020],
         [0.8227, 0.1782, 0.4245],
         ...,
         [0.6335, 0.6765, 0.7530],
         [0.5996, 0.9096, 0.4221],
         [0.3122, 0.2110, 0.6233]],

        ...,

        [[0.1400, 0.3558, 0.4320],
         [0.2702, 0.4899, 0.2504],
         [0.5053, 0.9419, 0.8247],
         ...,
         [0.7421, 0.7153, 0.6275],
         [0.4149, 0.3152, 0.9107],
         [0.1727, 0.2737, 0.3095]],

        [[0.7169, 0.9205, 0.3935],
         [0.6554, 0.8001, 0.6209],
         [0.

In [68]:
IMG.size()

torch.Size([224, 224, 3])

In [69]:
IMG.ndim

3

### Zeros and Ones

In [72]:
ZERO = torch.zeros(size=(23, 12, 3))

In [73]:
ZERO

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
     

In [74]:
ZERO.ndim

3

In [75]:
ONES = torch.ones(size=(2, 1, 2))

In [76]:
ONES

tensor([[[1., 1.]],

        [[1., 1.]]])

In [77]:
ONES.ndim

3

### Range of Tensors and Tensors Like

In [78]:
# Use torch.range()
torch.range(5, 10)

C:\Users\Shabnam\AppData\Local\Temp\ipykernel_12336\2203669239.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(5, 10)


tensor([ 5.,  6.,  7.,  8.,  9., 10.])

In [80]:
torch.arange(start=3, end=100, step=2)

tensor([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
        39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73,
        75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [88]:
# Tensors Like
RNG = torch.arange(start=7, end=1000, step=19, dtype=torch.float32)
torch.rand_like(input=RNG, dtype=torch.float32)

tensor([0.8735, 0.2740, 0.0392, 0.4047, 0.7082, 0.8675, 0.0562, 0.6960, 0.4600,
        0.1400, 0.2150, 0.1672, 0.3896, 0.4747, 0.5591, 0.8863, 0.4060, 0.8629,
        0.3440, 0.1734, 0.8674, 0.2928, 0.7231, 0.0371, 0.8913, 0.6012, 0.5994,
        0.0427, 0.9785, 0.0660, 0.5332, 0.5301, 0.5090, 0.2396, 0.9688, 0.1214,
        0.3289, 0.8991, 0.6250, 0.5554, 0.7729, 0.6402, 0.2221, 0.4417, 0.7245,
        0.6135, 0.1719, 0.3637, 0.0938, 0.1973, 0.2905, 0.7650, 0.5356])

### Tensor Datatypes

In [91]:
FLOAT = torch.tensor([4, 2, 13],
                     dtype=torch.float64,
                     device="cpu", # What device is your tensor on
                     requires_grad=False) # Whether to track gradients

In [92]:
FLOAT

tensor([ 4.,  2., 13.], dtype=torch.float64)

In [93]:
RAND1 = torch.rand(size=(2, 3, 5),
                   dtype=torch.float16)

In [94]:
RAND2 = torch.rand(size=(2, 3, 5),
                   dtype=torch.float32)

In [95]:
RAND1 * RAND2

tensor([[[0.4358, 0.3142, 0.7957, 0.7005, 0.0548],
         [0.1144, 0.0806, 0.3069, 0.1176, 0.1465],
         [0.2201, 0.1592, 0.8226, 0.3218, 0.2228]],

        [[0.4190, 0.0019, 0.7872, 0.0668, 0.0675],
         [0.0796, 0.3481, 0.1667, 0.0061, 0.2772],
         [0.1461, 0.0480, 0.1141, 0.0663, 0.1213]]])

### Getting information about tensors

**Note:** There are 3 big errors that we'll probably run into with PyTorch:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [96]:
IMG.shape

torch.Size([224, 224, 3])

In [97]:
IMG.dtype

torch.float32

In [98]:
IMG.device

device(type='cpu')

In [99]:
IMG.size()

torch.Size([224, 224, 3])

### Tensor Operations(Manipulation)

Operations include:
- Addition
- Subtraction
- Multiplication (element-wise)
- Division
- Matrix Multiplication

In [100]:
TENS1 = torch.rand([255, 255, 3], dtype=torch.float32)

In [101]:
TENS2 = torch.rand_like(input=TENS1, dtype=torch.float32)

In [102]:
torch.mul(TENS1, TENS2)

tensor([[[0.0173, 0.2697, 0.1789],
         [0.4366, 0.0090, 0.2950],
         [0.3693, 0.1461, 0.4551],
         ...,
         [0.9017, 0.5112, 0.5140],
         [0.1198, 0.4609, 0.6225],
         [0.2311, 0.4124, 0.2071]],

        [[0.1948, 0.0797, 0.6593],
         [0.2864, 0.1765, 0.0337],
         [0.6572, 0.1934, 0.3370],
         ...,
         [0.3589, 0.0811, 0.0365],
         [0.1385, 0.6798, 0.6549],
         [0.3805, 0.5523, 0.3175]],

        [[0.3795, 0.0138, 0.0191],
         [0.1418, 0.3934, 0.3139],
         [0.1922, 0.6889, 0.2074],
         ...,
         [0.1838, 0.2688, 0.2838],
         [0.0788, 0.5921, 0.0807],
         [0.1048, 0.0056, 0.0652]],

        ...,

        [[0.0967, 0.2454, 0.2553],
         [0.0401, 0.0821, 0.0427],
         [0.3358, 0.7291, 0.3569],
         ...,
         [0.4428, 0.1871, 0.0850],
         [0.0078, 0.3138, 0.2367],
         [0.5452, 0.4997, 0.0723]],

        [[0.0625, 0.1393, 0.5852],
         [0.5123, 0.0973, 0.5146],
         [0.