# Linear Algebra

## Introduction to NumPy and Matrices

In [19]:
import numpy as np

### Basics of NumPy

In [20]:
arr1 = np.arange(1, 100, 3)
arr1

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [21]:
arr2 = np.linspace(1, 100, 3)
arr2

array([  1. ,  50.5, 100. ])

In [22]:
arr1.shape

(33,)

In [23]:
arr1 = np.reshape(arr1, (3, 11))
arr1

array([[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31],
       [34, 37, 40, 43, 46, 49, 52, 55, 58, 61, 64],
       [67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97]])

In [24]:
arr1.shape

(3, 11)

In [25]:
arr1.ndim

2

In [26]:
arr1.size

33

In [27]:
arr1[:, 5:]

array([[16, 19, 22, 25, 28, 31],
       [49, 52, 55, 58, 61, 64],
       [82, 85, 88, 91, 94, 97]])

In [28]:
arr1[1:3]

array([[34, 37, 40, 43, 46, 49, 52, 55, 58, 61, 64],
       [67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97]])

### Solving Linear Systems

In [29]:
A = np.array([[1, 3],
             [4, 7]],
             dtype=np.dtype(float))

b = np.array([56, 3], dtype=np.dtype(float))

print(f"A is: \n {A}")
print(f"b is: \n {b}")

A is: 
 [[1. 3.]
 [4. 7.]]
b is: 
 [56.  3.]


In [30]:
x = np.linalg.solve(A, b)
print(f"Solution is: \n {x}")

Solution is: 
 [-76.6  44.2]


In [31]:
det = np.linalg.det(A)
print(f"Determinant of A is: {det}")

Determinant of A is: -4.999999999999999
